# Generated by Django 4.1.3 on 2022-11-07 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre de la cetgoria')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.CharField(max_length=200, verbose_name='Diagnostico')),
                ('mecanico', models.CharField(max_length=50, verbose_name='Mecanico')),
                ('fecha', models.DateField(max_length=9, verbose_name='Fecha')),
                ('materiales', models.CharField(max_length=200, verbose_name='Materiales')),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categorias')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre')),
                ('correo', models.CharField(max_length=20, verbose_name='Correo')),
                ('mensaje', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mensaje')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categorias')),
            ],
        ),
    ]
