# Generated by Django 4.1.3 on 2022-11-07 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20, verbose_name='Rut cliente')),
                ('destinatario', models.CharField(max_length=100, verbose_name='Destinatario')),
                ('monto', models.IntegerField(max_length=9, verbose_name='Monto')),
                ('fecha', models.DateField(max_length=9, verbose_name='Fecha')),
            ],
        ),
    ]
